theme: jekyll-theme-cayman
name: personal Blog
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

theme: jekyll-theme-leap-day
