# Site wide configuration

title: "personal Blog"
description: "记录自己的进步与想法，养成良好的习惯:文字表达能力、分享的习惯、坚持的习惯"
logo: logo.jpg # 120x120 px default image used for Twitter summary card
teaser: /teaser/default.jpg # 400x250 px default teaser image used in image archive grid
locale:
url:

default:
    -
        scope:
            type: "article"
        values:
            ads: false
            toc: false 


# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name: 王冲
  email: wangchongf123@gmail.com
  bio: 
  avatar: logo.jpg # 160x160 px image for author byline


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]

theme: jekyll-theme-leap-day