# Site wide configuration

title: "personal blog"
description: "每天学一点"
locale:
url:

default:
    -
        scope:
            type: "article"
        values:
            ads: false
            toc: false 


# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
kramdown:
    input: GFM
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner: 
  name: wangchong
  email: wangchongf123@gmail.com
  google:
    ad-client: "ca-pub-5984522345984184"
    ad-slot: "9439014959"
  bio: 


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
